# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  # Add your Flutter pods here
  
  # Firebase dependencies
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  
  # # Google Fonts
  # pod 'google_fonts'
  
  # # Cool Alert
  # pod 'CoolAlert'
  
  # # File Picker
  # pod 'file_picker'
  
  # # Syncfusion Flutter PDF Viewer
  # pod 'syncfusion_flutter_pdfviewer'

end

# Post-install setup
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
  end
end
